#!/usr/bin/env zsh
sudo pacman -S stow zsh
DOTFILES="~/.dotfiles-i3/"
STOW_FOLDERS=(i3 nvim polybar)
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd
